[tool.poetry]
name = "mk-ai-agent-test"
version = "0.1.0"
description = ""
authors = ["Marcin Korcz"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26.4"
openai = "^1.23.1"
pandas = "^2.2.2"
torch = "^2.2.2"
torchvision = "^0.17.2"
llama-index = "^0.10.33"
pydantic = "^2.7.1"
llama-index-core = "^0.10.33"
llama-index-readers-file = "^0.1.19"
llama-index-llms-ollama = "^0.1.3"
llama-index-embeddings-huggingface = "^0.2.0"
ipykernel = "^6.29.4"
ipywidgets = "^8.1.2"
langchain = "^0.2.15"
langchain-community = "^0.2.14"
langchain-openai = "^0.1.23"
pytest = "^8.3.3"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
package-mode = false
